#!/usr/bin/env bash
# One-shot Flexboard initialisation.
#
# Run once after cloning:
#   bash scripts/init.sh
#
# Safe to re-run: skips steps that are already complete.
#
# Default credentials (change after first login via http://localhost:17170):
#   Email:    admin@flexboard.localhost
#   Password: Test1234!   (or LLDAP_ADMIN_PASS if set in environment)
set -euo pipefail

DEX_CONFIG="config/dex.yaml"
ENV_FILE=".env"

step() { echo; echo "▶  $*"; }
log()  { echo "   $*"; }
err()  { echo "ERROR: $*" >&2; exit 1; }

# ── 1. Generate LLDAP_JWT_SECRET ─────────────────────────────────────────────
# Persisted in .env so that re-runs and restarts use the same secret.
# Docker Compose reads .env automatically from the project root.
step "Secrets"
if grep -q "^LLDAP_JWT_SECRET=" "$ENV_FILE" 2>/dev/null; then
  log "LLDAP_JWT_SECRET already present in $ENV_FILE — skipping."
else
  if command -v openssl >/dev/null 2>&1; then
    JWT_SECRET=$(openssl rand -hex 32)
  else
    JWT_SECRET=$(LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 64)
  fi
  {
    echo ""
    echo "# Auto-generated by scripts/init.sh — do not share or commit"
    echo "LLDAP_JWT_SECRET=$JWT_SECRET"
  } >> "$ENV_FILE"
  log "Generated LLDAP_JWT_SECRET → $ENV_FILE"
fi

# ── 2. Generate Dex config ────────────────────────────────────────────────────
step "OIDC configuration"
if [[ -f "$DEX_CONFIG" ]]; then
  log "Found existing $DEX_CONFIG — skipping generation."
else
  mkdir -p config
  DEX_BASE_URL="${FLEXBOARD_BASE_URL:-http://localhost}"
  ADMIN_PASS="${LLDAP_ADMIN_PASS:-Test1234!}"

  cat > "$DEX_CONFIG" <<EOF
issuer: $DEX_BASE_URL/dex

storage:
  type: memory

web:
  http: 0.0.0.0:5556

oauth2:
  skipApprovalScreen: true

staticClients:
  - id: flexboard-web
    name: Flexboard Web
    redirectURIs:
      - $DEX_BASE_URL/auth/callback
    public: true

connectors:
  - type: ldap
    id: ldap
    name: LLDAP
    config:
      host: lldap:3890
      insecureNoSSL: true
      bindDN: uid=admin,ou=people,dc=flexboard,dc=localhost
      bindPW: "$ADMIN_PASS"
      usernamePrompt: Email Address
      userSearch:
        baseDN: ou=people,dc=flexboard,dc=localhost
        filter: "(objectClass=person)"
        username: mail
        idAttr: uid
        emailAttr: mail
        nameAttr: cn
      groupSearch:
        baseDN: ou=groups,dc=flexboard,dc=localhost
        filter: "(objectClass=groupOfUniqueNames)"
        userMatchers:
          - userAttr: DN
            groupAttr: uniqueMember
        nameAttr: cn
EOF
  log "Created $DEX_CONFIG"
fi

# ── 3. Build and start all services ──────────────────────────────────────────
step "Building and starting all services"
# --force-recreate ensures containers from failed previous runs are replaced,
# picking up any config changes (e.g. a regenerated dex.yaml). Volumes are
# not affected, so existing MongoDB and LLDAP data are preserved on re-runs.
docker compose up -d --build --force-recreate

log "Waiting for LLDAP to become healthy (up to 60 s)…"
DEADLINE=$(( $(date +%s) + 60 ))
until docker compose ps lldap 2>/dev/null | grep -q "(healthy)"; do
  sleep 2
  (( $(date +%s) < DEADLINE )) || err "LLDAP did not become healthy within 60 s."
done

log "Waiting for Dex to become healthy (up to 60 s)…"
DEADLINE=$(( $(date +%s) + 60 ))
until docker compose ps dex 2>/dev/null | grep -q "(healthy)"; do
  sleep 2
  (( $(date +%s) < DEADLINE )) || err "Dex did not become healthy within 60 s."
done

log "All services ready."

ADMIN_PASS="${LLDAP_ADMIN_PASS:-Test1234!}"
BASE_URL="${FLEXBOARD_BASE_URL:-http://localhost}"

echo ""
echo "  +----------------------------------------------------+"
echo "  |  Flexboard  → ${BASE_URL}"
echo "  |  User mgmt  → ${BASE_URL}/useradmin"
echo "  |                                                    |"
echo "  |  Login:    admin@flexboard.localhost               |"
echo "  |  Password: ${ADMIN_PASS}                            |"
echo "  |                                                    |"
echo "  |  Add/remove users and reset passwords at           |"
echo "  |  ${BASE_URL}/useradmin"
echo "  +----------------------------------------------------+"
echo ""
