#!/usr/bin/env bash
# One-shot Flexboard initialisation.
#
# Run once after cloning:
#   bash scripts/init.sh
#
# Safe to re-run: skips steps that are already complete.
#
# Default credentials (change after first login via http://localhost/rauthy):
#   Email:    admin@flexboard.localhost
#   Password: Test1234!   (or RAUTHY_ADMIN_PASS if set in environment)
set -euo pipefail

ENV_FILE=".env"
RAUTHY_CONFIG="config/rauthy.toml"
BOOTSTRAP_DIR="config/rauthy-bootstrap"
BOOTSTRAP_CLIENTS="$BOOTSTRAP_DIR/clients.json"

step() { echo; echo "▶  $*"; }
log()  { echo "   $*"; }
err()  { echo "ERROR: $*" >&2; exit 1; }

if ! command -v openssl >/dev/null 2>&1; then
  err "openssl is required to generate secrets."
fi

# ── Parse FLEXBOARD_BASE_URL ──────────────────────────────────────────────────
BASE_URL="${FLEXBOARD_BASE_URL:-http://localhost}"
# Strip scheme
HOST_PATH="${BASE_URL#http://}"
HOST_PATH="${HOST_PATH#https://}"
# Host+port (no path)
HOST_PORT="${HOST_PATH%%/*}"
HOSTNAME_ONLY="${HOST_PORT%%:*}"
# Determine port: explicit in URL, or default for scheme
if [[ "$HOST_PORT" == *:* ]]; then
  PORT="${HOST_PORT##*:}"
elif [[ "$BASE_URL" == https://* ]]; then
  PORT=443
else
  PORT=80
fi
SCHEME="${BASE_URL%%://*}"

# PUB_URL for Rauthy: host(/port if non-standard)/rauthy — no scheme
if [[ "$PORT" == "80" && "$SCHEME" == "http" ]] || \
   [[ "$PORT" == "443" && "$SCHEME" == "https" ]]; then
  PUB_URL="${HOSTNAME_ONLY}/rauthy"
  # RAUTHY_ISSUER_URL: Rauthy always advertises https:// regardless of listen scheme
  RAUTHY_ISSUER_URL="https://${HOSTNAME_ONLY}/rauthy/auth/v1/"
else
  PUB_URL="${HOSTNAME_ONLY}:${PORT}/rauthy"
  RAUTHY_ISSUER_URL="https://${HOSTNAME_ONLY}:${PORT}/rauthy/auth/v1/"
fi
# WebAuthn origin must include explicit port (Rauthy requirement)
RP_ORIGIN="${SCHEME}://${HOSTNAME_ONLY}:${PORT}"

# ── 1. Generate Rauthy config.toml ───────────────────────────────────────────
# Rauthy requires several mandatory sections — all generated once and gitignored.
step "Rauthy config (config/rauthy.toml)"
if [[ -f "$RAUTHY_CONFIG" ]]; then
  log "Found existing $RAUTHY_CONFIG — skipping."
else
  SECRET_RAFT=$(openssl rand -hex 32)
  SECRET_API=$(openssl rand -hex 32)
  ENC_KID=$(openssl rand -hex 8)
  ENC_KEY=$(openssl rand -base64 32)
  mkdir -p config
  cat > "$RAUTHY_CONFIG" <<EOF
# Rauthy configuration for Flexboard — generated by scripts/init.sh
# Do not commit this file (contains secrets).
# Reference: https://sebadob.github.io/rauthy/config/config.html

[server]
# Public URL without scheme — Rauthy always uses https:// for the OIDC issuer.
# For nginx subpath proxy: strip the scheme from FLEXBOARD_BASE_URL and append /rauthy.
pub_url = '${PUB_URL}'
port_http = 8080

[cluster]
# Required even for single-node deployments (embedded Hiqlite/Raft database).
node_id = 1
nodes = ['1 localhost:8100 localhost:8200']
secret_raft = '${SECRET_RAFT}'
secret_api  = '${SECRET_API}'

[encryption]
# Encryption key for sensitive data stored in the database.
keys = ['${ENC_KID}/${ENC_KEY}']
key_active = '${ENC_KID}'

[webauthn]
# Required even if passkeys are not used. Must match the app's public origin.
rp_id = '${HOSTNAME_ONLY}'
rp_origin = '${RP_ORIGIN}'
EOF
  log "Created $RAUTHY_CONFIG"
fi

# ── 2. Persist derived URLs to .env ──────────────────────────────────────────
# RAUTHY_ISSUER_URL is always https:// — Rauthy forces this regardless of
# the deployment's listen scheme. Used by the backend for JWT iss validation
# and by the frontend for the canonical issuer in /config.js.
step "Environment (.env)"
if grep -q "^RAUTHY_ISSUER_URL=" "$ENV_FILE" 2>/dev/null; then
  log "RAUTHY_ISSUER_URL already present in $ENV_FILE — skipping."
else
  {
    echo ""
    echo "# Auto-generated by scripts/init.sh"
    echo "RAUTHY_ISSUER_URL=${RAUTHY_ISSUER_URL}"
  } >> "$ENV_FILE"
  log "Wrote RAUTHY_ISSUER_URL=${RAUTHY_ISSUER_URL} → $ENV_FILE"
fi

# ── 3. Generate Rauthy bootstrap client config ────────────────────────────────
# Always regenerate — the redirect URIs are derived from BASE_URL so this file
# must stay in sync if init.sh is re-run with a different URL.
# (Only takes effect on a fresh Rauthy DB; updating an existing client requires
# using the admin UI at BASE_URL/rauthy.)
step "OIDC client bootstrap"
mkdir -p "$BOOTSTRAP_DIR"
  cat > "$BOOTSTRAP_CLIENTS" <<EOF
[
  {
    "id": "flexboard-web",
    "name": "Flexboard Web",
    "secret": null,
    "confidential": false,
    "redirect_uris": ["${BASE_URL}/auth/callback"],
    "post_logout_redirect_uris": ["${BASE_URL}"],
    "allowed_origins": ["${BASE_URL}"],
    "enabled": true,
    "flows_enabled": ["authorization_code"],
    "access_token_alg": "RS256",
    "id_token_alg": "RS256",
    "auth_code_lifetime": 60,
    "access_token_lifetime": 1800,
    "force_mfa": false,
    "challenges": ["S256"],
    "scopes": ["openid", "profile", "email"],
    "default_scopes": ["openid", "profile", "email"]
  }
]
EOF
log "Wrote $BOOTSTRAP_CLIENTS"

# ── 4. Build and start all services ──────────────────────────────────────────
step "Building and starting all services"
docker compose up -d --build --force-recreate

log "Waiting for Rauthy to become healthy (up to 90 s)…"
DEADLINE=$(( $(date +%s) + 90 ))
# Note: Docker healthcheck is disabled for the Rauthy container (it has no shell/curl/wget).
# Poll the Rauthy health endpoint from the host instead.
until curl -sf "http://localhost:${RAUTHY_PORT:-8080}/auth/v1/health" >/dev/null 2>&1; do
  sleep 3
  (( $(date +%s) < DEADLINE )) || err "Rauthy did not become healthy within 90 s. Check: docker compose logs rauthy"
done

log "All services ready."

ADMIN_PASS="${RAUTHY_ADMIN_PASS:-Test1234!}"

echo ""
echo "  +----------------------------------------------------+"
echo "  |  Flexboard  → ${BASE_URL}"
echo "  |  Admin UI   → ${BASE_URL}/rauthy"
echo "  |                                                    |"
echo "  |  Login:    admin@flexboard.localhost               |"
echo "  |  Password: ${ADMIN_PASS}                            |"
echo "  |                                                    |"
echo "  |  Add/remove users and manage accounts at           |"
echo "  |  ${BASE_URL}/rauthy                                |"
echo "  +----------------------------------------------------+"
echo ""
