#!/usr/bin/env bash
# One-shot Flexboard initialisation.
#
# Run once after cloning:
#   bash scripts/init.sh
#
# Safe to re-run: skips steps that are already complete.
#
# Default credentials (change after first login via http://localhost/rauthy):
#   Email:    admin@flexboard.localhost
#   Password: Test1234!   (or RAUTHY_ADMIN_PASS if set in environment)
set -euo pipefail

ENV_FILE=".env"
BOOTSTRAP_DIR="config/rauthy-bootstrap"
BOOTSTRAP_CLIENTS="$BOOTSTRAP_DIR/clients.json"

step() { echo; echo "▶  $*"; }
log()  { echo "   $*"; }
err()  { echo "ERROR: $*" >&2; exit 1; }

# ── 1. Generate Rauthy encryption keys ───────────────────────────────────────
# Persisted in .env so that re-runs and restarts use the same key.
# Docker Compose reads .env automatically from the project root.
step "Secrets"
if grep -q "^RAUTHY_ENC_KEYS=" "$ENV_FILE" 2>/dev/null; then
  log "RAUTHY_ENC_KEYS already present in $ENV_FILE — skipping."
else
  if ! command -v openssl >/dev/null 2>&1; then
    err "openssl is required to generate encryption keys."
  fi
  KID=$(openssl rand -hex 8)
  KEY=$(openssl rand -base64 32)
  {
    echo ""
    echo "# Auto-generated by scripts/init.sh — do not share or commit"
    echo "RAUTHY_ENC_KEYS=${KID}/${KEY}"
    echo "RAUTHY_ENC_KEY_ACTIVE=${KID}"
  } >> "$ENV_FILE"
  log "Generated RAUTHY_ENC_KEYS → $ENV_FILE"
fi

# ── 2. Generate Rauthy bootstrap client config ────────────────────────────────
step "OIDC client bootstrap"
if [[ -f "$BOOTSTRAP_CLIENTS" ]]; then
  log "Found existing $BOOTSTRAP_CLIENTS — skipping generation."
else
  mkdir -p "$BOOTSTRAP_DIR"
  BASE_URL="${FLEXBOARD_BASE_URL:-http://localhost}"

  cat > "$BOOTSTRAP_CLIENTS" <<EOF
[
  {
    "id": "flexboard-web",
    "name": "Flexboard Web",
    "secret": null,
    "redirect_uris": ["${BASE_URL}/auth/callback"],
    "post_logout_redirect_uris": ["${BASE_URL}"],
    "allowed_origins": ["${BASE_URL}"],
    "enabled": true,
    "flows_enabled": ["authorization_code"],
    "access_token_alg": "RS256",
    "id_token_alg": "RS256",
    "challenges": ["S256"],
    "scopes": ["openid", "profile", "email"],
    "default_scopes": ["openid", "profile", "email"]
  }
]
EOF
  log "Created $BOOTSTRAP_CLIENTS"
fi

# ── 3. Build and start all services ──────────────────────────────────────────
step "Building and starting all services"
# --force-recreate ensures containers from failed previous runs are replaced,
# picking up any config changes. Volumes are not affected, so existing MongoDB
# and Rauthy data are preserved on re-runs.
docker compose up -d --build --force-recreate

log "Waiting for Rauthy to become healthy (up to 90 s)…"
DEADLINE=$(( $(date +%s) + 90 ))
until docker compose ps rauthy 2>/dev/null | grep -q "(healthy)"; do
  sleep 3
  (( $(date +%s) < DEADLINE )) || err "Rauthy did not become healthy within 90 s."
done

log "All services ready."

ADMIN_PASS="${RAUTHY_ADMIN_PASS:-Test1234!}"
BASE_URL="${FLEXBOARD_BASE_URL:-http://localhost}"

echo ""
echo "  +----------------------------------------------------+"
echo "  |  Flexboard  → ${BASE_URL}"
echo "  |  Admin UI   → ${BASE_URL}/rauthy"
echo "  |                                                    |"
echo "  |  Login:    admin@flexboard.localhost               |"
echo "  |  Password: ${ADMIN_PASS}                            |"
echo "  |                                                    |"
echo "  |  Add/remove users and manage accounts at           |"
echo "  |  ${BASE_URL}/rauthy                                |"
echo "  +----------------------------------------------------+"
echo ""
